/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    hr_cms_users: HrCmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    hr_cms_users: HrCmsUser;
    hr_media: HrMedia;
    hr_categories: HrCategory;
    hr_authors: HrAuthor;
    hr_articles: HrArticle;
    hr_breaking: HrBreaking;
    hr_ad_creatives: HrAdCreative;
    hr_integration_receipts: HrIntegrationReceipt;
    hr_audit_events: HrAuditEvent;
    hr_corrections: HrCorrection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    hr_cms_users: HrCmsUsersSelect<false> | HrCmsUsersSelect<true>;
    hr_media: HrMediaSelect<false> | HrMediaSelect<true>;
    hr_categories: HrCategoriesSelect<false> | HrCategoriesSelect<true>;
    hr_authors: HrAuthorsSelect<false> | HrAuthorsSelect<true>;
    hr_articles: HrArticlesSelect<false> | HrArticlesSelect<true>;
    hr_breaking: HrBreakingSelect<false> | HrBreakingSelect<true>;
    hr_ad_creatives: HrAdCreativesSelect<false> | HrAdCreativesSelect<true>;
    hr_integration_receipts: HrIntegrationReceiptsSelect<false> | HrIntegrationReceiptsSelect<true>;
    hr_audit_events: HrAuditEventsSelect<false> | HrAuditEventsSelect<true>;
    hr_corrections: HrCorrectionsSelect<false> | HrCorrectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: HrCmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface HrCmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_cms_users".
 */
export interface HrCmsUser {
  id: string;
  display_name?: string | null;
  /**
   * Deny-by-default newsroom role. AI service accounts cannot publish or operate advertising.
   */
  role: 'super_admin' | 'managing_editor' | 'copy_editor' | 'reporter' | 'ad_ops' | 'analyst' | 'ai_service';
  desk?: ('Audience' | 'Business' | 'Civic' | 'Culture' | 'Defense & port' | 'History' | 'Service') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'hr_cms_users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_media".
 */
export interface HrMedia {
  id: string;
  /**
   * Accessibility alt text — describe the image.
   */
  alt: string;
  caption?: string | null;
  photographer?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_categories".
 */
export interface HrCategory {
  id: string;
  name: string;
  slug: string;
  order?: number | null;
  accent_hex?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_authors".
 */
export interface HrAuthor {
  id: string;
  name: string;
  slug: string;
  bio?: string | null;
  avatar_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * High-throughput story desk with explicit ownership, quality, provenance, and publishing gates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_articles".
 */
export interface HrArticle {
  id: string;
  short_id: string;
  slug: string;
  title: string;
  dek?: string | null;
  kicker?: string | null;
  section?: (string | null) | HrCategory;
  author?: (string | null) | HrAuthor;
  body_lexical?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero_media?: (string | null) | HrMedia;
  hero_image_url?: string | null;
  hero_image_alt?: string | null;
  /**
   * Rights, source, credit, and transfer metadata from connected systems.
   */
  media_provenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflow_stage:
    | 'intake'
    | 'reporting'
    | 'draft'
    | 'changes_requested'
    | 'copy_edit'
    | 'legal_review'
    | 'ready'
    | 'scheduled'
    | 'published';
  priority: 'standard' | 'urgent' | 'breaking';
  desk?: ('audience' | 'business' | 'civic' | 'culture' | 'defense_port' | 'history' | 'service') | null;
  assignee?: (string | null) | HrCmsUser;
  publish_at?: string | null;
  published_at?: string | null;
  /**
   * Historical event date, when applicable.
   */
  event_date?: string | null;
  read_time_min?: number | null;
  is_pro?: boolean | null;
  /**
   * Names, figures, dates, quotations, and claims have been verified.
   */
  fact_checked?: boolean | null;
  /**
   * Sources and methodology are attached or disclosed.
   */
  sources_checked?: boolean | null;
  /**
   * Media ownership, license, credit, and alt text are verified.
   */
  rights_checked?: boolean | null;
  /**
   * AI, sponsorship, conflicts, and material limitations are disclosed.
   */
  disclosure_checked?: boolean | null;
  /**
   * Normalized topic tags. Seed Refiner values land here for human review.
   */
  story_tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * All submitted bylines and external author identifiers.
   */
  bylines?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Model, prompt version, source set, safety results, and human editor receipt.
   */
  ai_provenance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source_origin?: ('payload' | 'hunts_pointe' | 'api' | 'import') | null;
  source_document_id?: string | null;
  source_version?: number | null;
  ingest_key?: string | null;
  /**
   * Unknown external taxonomy is held here instead of silently creating a production section.
   */
  suggested_section?: string | null;
  last_ingested_at?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_breaking".
 */
export interface HrBreaking {
  id: string;
  headline: string;
  description?: string | null;
  image_url?: string | null;
  article?: (string | null) | HrArticle;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_ad_creatives".
 */
export interface HrAdCreative {
  id: string;
  advertiser: string;
  slot_targets?: ('article-inline' | 'sidebar' | 'home-feed')[] | null;
  creative_url: string;
  dest_url: string;
  weight?: number | null;
  flight_start?: string | null;
  flight_end?: string | null;
  /**
   * Only a passed scan plus human approval can set the serving trust flag.
   */
  scan_status: 'pending' | 'scanning' | 'passed' | 'failed' | 'quarantined';
  human_approved?: boolean | null;
  scan_details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewed_by?: (string | null) | HrCmsUser;
  reviewed_at?: string | null;
  /**
   * Derived trust flag. Requires scan_status=passed and human_approved=true. HR_flag_ad_anomalies() may still auto-expire anomalous creatives.
   */
  is_trusted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable-ish receipt trail for Seed Refiner and other server-to-server draft ingestion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_integration_receipts".
 */
export interface HrIntegrationReceipt {
  id: string;
  idempotency_key: string;
  source: 'hunts_pointe' | 'api' | 'import';
  source_document_id?: string | null;
  source_version?: number | null;
  payload_hash: string;
  status: 'processing' | 'completed' | 'failed';
  article?: (string | null) | HrArticle;
  error_code?: string | null;
  received_at: string;
  last_seen_at: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only operational history. Mutations are server-only and every record carries actor/object hashes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_audit_events".
 */
export interface HrAuditEvent {
  id: string;
  action: string;
  actor_email: string;
  actor_id?: string | null;
  actor_role:
    'system' | 'super_admin' | 'managing_editor' | 'copy_editor' | 'reporter' | 'ad_ops' | 'analyst' | 'ai_service';
  object_type: string;
  object_id?: string | null;
  before_hash?: string | null;
  after_hash?: string | null;
  reason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public corrections log (WS-20). Reports from readers arrive by email via /api/corrections → corrections@ — after review, add the correction here to publish it at the bottom of the affected article. Never write directly from a public form; this collection is staff-authored only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_corrections".
 */
export interface HrCorrection {
  id: string;
  article: string | HrArticle;
  description: string;
  corrected_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'hr_cms_users';
        value: string | HrCmsUser;
      } | null)
    | ({
        relationTo: 'hr_media';
        value: string | HrMedia;
      } | null)
    | ({
        relationTo: 'hr_categories';
        value: string | HrCategory;
      } | null)
    | ({
        relationTo: 'hr_authors';
        value: string | HrAuthor;
      } | null)
    | ({
        relationTo: 'hr_articles';
        value: string | HrArticle;
      } | null)
    | ({
        relationTo: 'hr_breaking';
        value: string | HrBreaking;
      } | null)
    | ({
        relationTo: 'hr_ad_creatives';
        value: string | HrAdCreative;
      } | null)
    | ({
        relationTo: 'hr_integration_receipts';
        value: string | HrIntegrationReceipt;
      } | null)
    | ({
        relationTo: 'hr_audit_events';
        value: string | HrAuditEvent;
      } | null)
    | ({
        relationTo: 'hr_corrections';
        value: string | HrCorrection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'hr_cms_users';
    value: string | HrCmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'hr_cms_users';
    value: string | HrCmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_cms_users_select".
 */
export interface HrCmsUsersSelect<T extends boolean = true> {
  display_name?: T;
  role?: T;
  desk?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_media_select".
 */
export interface HrMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  photographer?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_categories_select".
 */
export interface HrCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  accent_hex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_authors_select".
 */
export interface HrAuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_articles_select".
 */
export interface HrArticlesSelect<T extends boolean = true> {
  short_id?: T;
  slug?: T;
  title?: T;
  dek?: T;
  kicker?: T;
  section?: T;
  author?: T;
  body_lexical?: T;
  hero_media?: T;
  hero_image_url?: T;
  hero_image_alt?: T;
  media_provenance?: T;
  workflow_stage?: T;
  priority?: T;
  desk?: T;
  assignee?: T;
  publish_at?: T;
  published_at?: T;
  event_date?: T;
  read_time_min?: T;
  is_pro?: T;
  fact_checked?: T;
  sources_checked?: T;
  rights_checked?: T;
  disclosure_checked?: T;
  story_tags?: T;
  bylines?: T;
  ai_provenance?: T;
  source_origin?: T;
  source_document_id?: T;
  source_version?: T;
  ingest_key?: T;
  suggested_section?: T;
  last_ingested_at?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_breaking_select".
 */
export interface HrBreakingSelect<T extends boolean = true> {
  headline?: T;
  description?: T;
  image_url?: T;
  article?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_ad_creatives_select".
 */
export interface HrAdCreativesSelect<T extends boolean = true> {
  advertiser?: T;
  slot_targets?: T;
  creative_url?: T;
  dest_url?: T;
  weight?: T;
  flight_start?: T;
  flight_end?: T;
  scan_status?: T;
  human_approved?: T;
  scan_details?: T;
  reviewed_by?: T;
  reviewed_at?: T;
  is_trusted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_integration_receipts_select".
 */
export interface HrIntegrationReceiptsSelect<T extends boolean = true> {
  idempotency_key?: T;
  source?: T;
  source_document_id?: T;
  source_version?: T;
  payload_hash?: T;
  status?: T;
  article?: T;
  error_code?: T;
  received_at?: T;
  last_seen_at?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_audit_events_select".
 */
export interface HrAuditEventsSelect<T extends boolean = true> {
  action?: T;
  actor_email?: T;
  actor_id?: T;
  actor_role?: T;
  object_type?: T;
  object_id?: T;
  before_hash?: T;
  after_hash?: T;
  reason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_corrections_select".
 */
export interface HrCorrectionsSelect<T extends boolean = true> {
  article?: T;
  description?: T;
  corrected_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}